import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import { FaPlay } from "react-icons/fa";
import SpecialBoxFrame from '@/components/special-box-frame'
import { IoMdArrowDown } from "react-icons/io";
import { FaHeart } from "react-icons/fa";
import { IoArrowDownCircleOutline } from "react-icons/io5";
import Footer from '@/components/footer'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
       <Header />
 
       <div className='container-3'>
        <div className='wrapper-3'>
          
          <div className='page-cpvdl'>
            <div className='vlvldfpppspsp'>
              <h1>About us</h1>

              <p>
              Welcome to [Your Company Name], where [brief description of your mission or purpose]. At [Your Company Name], we are dedicated to [describe the core values or goals of your organization].
              </p>

              <h2>Our Mission</h2>
              <p>[Your Company Name] was founded with a singular mission: [insert mission statement here]. We believe in [core belief or value] and strive to [specific actions or objectives related to your mission].</p>

              <h2>What Sets Us Apart</h2>
              <p>
              At [Your Company Name], we pride ourselves on [highlight a unique aspect of your organization]. Whether it's our commitment to [specific cause], our innovative approach to [industry], or our unwavering dedication to [core value], we aim to [impact or change you hope to make].
              </p>

              <h2>Our Team</h2>
              <p>
              Meet the passionate individuals behind [Your Company Name]. Our team is composed of [brief description of key team members], each bringing their unique expertise and dedication to [specific aspect of your work]. Together, we work tirelessly to [achieve your mission or goals].
              </p>

              <h2>How We Started</h2>
              <p>
              [Your Company Name] started as a [brief history or story of the organization's origins]. Since then, we have [highlight key milestones or achievements], growing into the organization we are today.
              </p>

              <h2>Get Involved</h2>
              <p>
              Join us on our journey to [mission or goal]. Whether you're a supporter, volunteer, or partner, there are many ways to get involved and make a positive impact with [Your Company Name]. Explore our website to [highlight key areas or initiatives], and together, let's make a difference.
              </p>
            </div>
            </div>
            </div>
        </div>

      <Footer className='ablcdp2dw'/>
 
      
    </>
  )
} 
