import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import { FaPlay } from "react-icons/fa";
import SpecialBoxFrame from '@/components/special-box-frame'
import { IoMdArrowDown } from "react-icons/io";
import { FaHeart } from "react-icons/fa";
import { IoArrowDownCircleOutline } from "react-icons/io5";
import Footer from '@/components/footer'
import HeaderNew from '@/components/header-new'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <HeaderNew noFixed={true}/>


      <div className='container'>
        <div className='wrapper'>
            <div className='contact-us-adolpkoda'>

              <div className='qq-cal-l'>

                <div className='lp-cpsl--pcslp'>
                  <h1>Contact us</h1>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,
  molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum
  numquam blanditiis harum quisquam eius sed odit fugiat iusto.</p>
                  <ul className='dlsapp-xpap'>
                    <li>Sint commodi repudiandae consequuntur voluptatum</li>
                    <li>Blanditiis harum quisquam eius sed odit fugiat iusto</li>
                    <li>Molestiae quas vel sint commodi repudiandae</li>
                    <li>Sint commodi repudiandae consequuntur voluptatum</li>
                    <li>Blanditiis harum quisquam eius sed odit fugiat iusto</li>
                  </ul>
                  
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,
  molestiae quas vel sint commodi.</p>
                </div>

              </div>
              
              <div className='qq-cal-l-1'>
                <div className='l-as--s-appxla'>
                  <div className='fwlpflwp'>

                    <div className='lcpsa-lasplxxx'>
                      <label>Full name</label>
                      <input placeholder='Name'/>
                    </div>

                    <div className='lcpsa-lasplxxx'>
                      <label>Email</label>
                      <input placeholder='Email address'/>
                    </div>



                    <div className='lcpsa-lasplxxx'>
                      <label>Message</label>
                      <input placeholder='Message'/>
                    </div>

                    <div className='ldpsa-lcspl'>
                      <button>Send</button>
                    </div>

                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>

      <Footer className='ablcdp2dw'/>
 
      
    </>
  )
} 
