import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import { FaPlay } from "react-icons/fa";
import SpecialBoxFrame from '@/components/special-box-frame'
import { IoMdArrowDown } from "react-icons/io";
import { FaHeart } from "react-icons/fa";
import { IoArrowDownCircleOutline } from "react-icons/io5";
import Footer from '@/components/footer'
import HeaderNew from '@/components/header-new'


const inter = Inter({ subsets: ['latin'] })

export default function PrivacyPolicy() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderNew noFixed={true}/>

      <div className='container'>
        <div className='wrapper'>
          
          <div className='page-cpvdl'>
            <div className='vlvldfpppspsp'>
              <h1>Cookie Policy</h1>


              <p>Effective Date: 09.01.2024</p>

              <h2>1. What Are Cookies?</h2>

              <p>Cookies are small pieces of data stored on your device (computer or mobile device) that track and remember your activities on our website. They are widely used to make websites work more efficiently and provide a better user experience.</p>

              <h2>2. How We Use Cookies</h2>

              <p>We use cookies for various purposes, including:</p>

              <ul>
                  <li>2.1 <strong>Essential Cookies:</strong> Necessary for the basic functionality of our website.</li>
                  <li>2.2 <strong>Analytics Cookies:</strong> Help us understand how visitors interact with our website by collecting and reporting information anonymously.</li>
                  <li>2.3 <strong>Preference Cookies:</strong> Enable our website to remember your preferences and settings.</li>
                  <li>2.4 <strong>Marketing Cookies:</strong> Used to deliver relevant advertisements and promotions based on your interests.</li>
              </ul>

              <h2>3. Your Consent</h2>

              <p>By using our website, you consent to the use of cookies as described in this Cookies Policy. If you do not agree to our use of cookies, you may disable or manage cookies through your browser settings.</p>

              <h2>4. Disabling Cookies</h2>

              <p>You can disable cookies through your browser settings. Please note that disabling certain cookies may impact the functionality and user experience of our website.</p>

              <h2>5. Changes to this Cookies Policy</h2>

              <p>We may update this Cookies Policy to reflect changes in our practices. Please review the policy periodically.</p>

              <h2>6. Contact Us</h2>

              <p>If you have any questions or concerns about this Cookies Policy, please contact us at contact@riseupgram.com.</p>


            </div>
          </div>

        </div>
      </div>

      <Footer className='ablcdp2dw'/>
 
      
    </>
  )
} 
