import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import { FaPlay } from "react-icons/fa";
import SpecialBoxFrame from '@/components/special-box-frame'
import { IoMdArrowDown } from "react-icons/io";
import { FaHeart } from "react-icons/fa";
import { IoArrowDownCircleOutline } from "react-icons/io5";
import Footer from '@/components/footer'
import HeaderNew from '@/components/header-new'


const inter = Inter({ subsets: ['latin'] })

export default function PrivacyPolicy() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <HeaderNew noFixed={true}/>

      <div className='container'>
        <div className='wrapper'>
          
          <div className='page-cpvdl'>
            <div className='vlvldfpppspsp'>
              <h1>Privacy Policy</h1>


              <p>Effective Date: 09.01.2024</p>

              <h2>1. Information We Collect</h2>

              <ul>
                <li>1.1 <strong>Personal Information:</strong> We may collect personal information, such as your name, email address, and contact details when you create an account or make a donation.</li>
                <li>1.2 <strong>Payment Information:</strong> When you make a donation on our website, we collect payment information, including credit card details. This information is securely processed by our third-party payment processor, and we do not store it on our servers.</li>
                <li>1.3 <strong>User Content:</strong> Information you provide in comments, messages, or other forms of user-generated content on our platform.</li>
                <li>1.4 <strong>Usage Information:</strong> We automatically collect information about your interactions with our website, such as the pages you visit, the time and date of access, and your IP address.</li>
            </ul>

            <h2>2. How We Use Your Information</h2>

            <ul>
                <li>2.1 <strong>Donations:</strong> We use your personal and payment information to process and facilitate your donations on our platform.</li>
                <li>2.2 <strong>Communication:</strong> We may use your email address to send you updates about your donations, newsletters, and promotional content. You can opt-out of promotional emails at any time.</li>
                <li>2.3 <strong>Improvement of Services:</strong> We use collected data to analyze and enhance the functionality and user experience of our website.</li>
            </ul>

            <h2>3. How We Share Your Information</h2>

            <ul>
                <li>3.1 <strong>Third-Party Service Providers:</strong> We may share your information with trusted third-party service providers, such as payment processors, to facilitate our services.</li>
                <li>3.2 <strong>Legal Compliance:</strong> We may disclose your information when required by law or in response to valid legal requests.</li>
            </ul>

            <h2>4. Security Measures</h2>

            <p>We implement industry-standard security measures to protect your personal information. However, no method of transmission over the internet or electronic storage is 100% secure.</p>

            <h2>5. Your Choices</h2>

            <p>You can manage your communication preferences by adjusting your account settings or unsubscribing from promotional emails.</p>

            <h2>6. Changes to this Privacy Policy</h2>

            <p>We may update this Privacy Policy to reflect changes in our practices. Please review the policy periodically.</p>

            <h2>7. Contact Us</h2>

            <p>If you have any questions or concerns about this Privacy Policy, please contact us at [your contact email].</p>


            </div>
          </div>

        </div>
      </div>

      <Footer className='ablcdp2dw'/>
 
      
    </>
  )
} 
