import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import { FaPlay } from "react-icons/fa";
import SpecialBoxFrame from '@/components/special-box-frame'
import { IoMdArrowDown } from "react-icons/io";
import { FaHeart } from "react-icons/fa";
import { IoArrowDownCircleOutline } from "react-icons/io5";
import Footer from '@/components/footer'
import Link from 'next/link'
import HeaderNew from '@/components/header-new'


const inter = Inter({ subsets: ['latin'] })

export default function Projects() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <HeaderNew />



      <div className='container'> 
        <div className='wrapper'> 
          <div className='vlvdsppvsddsdcvd'>
            <div className='vlvlcldspppfwep'>
              <h1>Projects</h1>
            </div>

            <div className='list-fundraisers-row vkkvlfdvldfflvlf'>


                <Link href="/project/ovfovld" className='vlvfdlppspps'>
                  <div className='fundraiser-single-l-r'>
                    <div className='fslr-p'>
                        <div className='fslr-p-img'>
                          <img src="/tsclv.png" />
                        </div>
                        <div className='flpr-pet-te'>
                          <h1>Help Turkey and Syira <br/>Earthquake Relief Fund</h1>

                          <p>Since 2006, SOIL has been working in urban...</p>
                        </div>

                        <div className='lvldvfdps-raised'>
                          <span>$90,294</span>
                          <label>raised  of $100,000 goal</label>
                        </div>

                        <div className='lslv-ra-goal'>
                          <div className='lsvl-goal-progess-bar'>
                            <div className='lvl-pb-progress'></div>
                          </div>
                        </div>

                        <div className='slc-total-supporters'>
                          <div className='cpvpvpvfffw1ew'>
                            <div className='clvlvfpppp'>
                              <FaHeart size={20} color='#E86273'/>
                            </div>
                            <div className='pvpd-vdsvs'>
                              <span>10,583 Supporters</span>
                            </div>
                          </div>
                          <div className='d-type-dpv'>
                            <span>Medical</span>
                          </div>
                        </div>
                    </div>
                  </div>
                </Link>

                <Link href="/project/ovfovld" className='vlvfdlppspps'>
                  <div className='fundraiser-single-l-r'>
                    <div className='fslr-p'>
                        <div className='fslr-p-img'>
                          <img src="/tsclv.png" />
                        </div>
                        <div className='flpr-pet-te'>
                          <h1>Help Turkey and Syira <br/>Earthquake Relief Fund</h1>

                          <p>Since 2006, SOIL has been working in urban...</p>
                        </div>

                        <div className='lvldvfdps-raised'>
                          <span>$90,294</span>
                          <label>raised  of $100,000 goal</label>
                        </div>

                        <div className='lslv-ra-goal'>
                          <div className='lsvl-goal-progess-bar'>
                            <div className='lvl-pb-progress'></div>
                          </div>
                        </div>

                        <div className='slc-total-supporters'>
                          <div className='cpvpvpvfffw1ew'>
                            <div className='clvlvfpppp'>
                              <FaHeart size={20} color='#E86273'/>
                            </div>
                            <div className='pvpd-vdsvs'>
                              <span>10,583 Supporters</span>
                            </div>
                          </div>
                          <div className='d-type-dpv'>
                            <span>Medical</span>
                          </div>
                        </div>
                    </div>
                  </div>
                </Link>

                <Link href="/project/ovfovld" className='vlvfdlppspps'>
                  <div className='fundraiser-single-l-r'>
                    <div className='fslr-p'>
                        <div className='fslr-p-img'>
                          <img src="/tsclv.png" />
                        </div>
                        <div className='flpr-pet-te'>
                          <h1>Help Turkey and Syira <br/>Earthquake Relief Fund</h1>

                          <p>Since 2006, SOIL has been working in urban...</p>
                        </div>

                        <div className='lvldvfdps-raised'>
                          <span>$90,294</span>
                          <label>raised  of $100,000 goal</label>
                        </div>

                        <div className='lslv-ra-goal'>
                          <div className='lsvl-goal-progess-bar'>
                            <div className='lvl-pb-progress'></div>
                          </div>
                        </div>

                        <div className='slc-total-supporters'>
                          <div className='cpvpvpvfffw1ew'>
                            <div className='clvlvfpppp'>
                              <FaHeart size={20} color='#E86273'/>
                            </div>
                            <div className='pvpd-vdsvs'>
                              <span>10,583 Supporters</span>
                            </div>
                          </div>
                          <div className='d-type-dpv'>
                            <span>Medical</span>
                          </div>
                        </div>
                    </div>
                  </div>
                </Link>

              </div>
          </div>
        </div>
      </div>
 

      <Footer className='ablcdp2dw'/>
 
      
    </>
  )
} 
