import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import { FaPlay } from "react-icons/fa";
import SpecialBoxFrame from '@/components/special-box-frame'
import { IoMdArrowDown } from "react-icons/io";
import { FaHeart } from "react-icons/fa";
import { IoArrowDownCircleOutline } from "react-icons/io5";
import Footer from '@/components/footer'
import Link from 'next/link'
import HeaderNew from '@/components/header-new'
import { FiDelete, FiSearch } from 'react-icons/fi'
import { useEffect, useRef, useState } from 'react'
import { useGetFundraisersQuery } from '@/slices/fundraisers/fundraisersApiSlices'
import { FILES_URL } from '../../config'


const inter = Inter({ subsets: ['latin'] })

export default function Projects() {

  const [inputVal, setInputValue] = useState<string>('');
  const [nearYouOrTrending, setNYorTr] = useState<string>('trending')
  const inputRef = useRef<HTMLInputElement>(null);

  const { data: all_fundraisers, refetch: nbr, isError:nibe, isLoading: nbl, isSuccess:nbs, error:nbe } = useGetFundraisersQuery([]);


  useEffect(()=>{
    if(inputRef){
      inputRef.current?.focus();
    }
  },[]);

  const calculateProgressOfFundraiser = (raised: number, goal: number) => {
    const percentage = (raised / goal) * 100;

    // Ensure the percentage is capped at 100%
    return Math.min(percentage, 100);
  }

  function formatDonationAmount(inputValue: number) {
  
    const formattedAmount = new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(inputValue);
  
    return formattedAmount;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <HeaderNew noFixed={true}/>

      <div className='container'>
        <div className='wrapper'>
          <div className='lzppx---zpasppxlal-as'>
              <div className='lzp-c-app---asp'>
                  <h1>Search fundraisers on RiseUpGram</h1>
                  <p>Find fundraisers by location, title, keyword, or a person’s name</p>
              </div>
              <div className='pz--appz-psdlalpdpass'>
                  <div className='zp-ppadplldsl'>
                    <FiSearch  size={18} color='#333333'/>
                  </div>
                  <input 
                    placeholder='Search' 
                    onChange={(e)=>{setInputValue(e.target.value)}}
                    value={inputVal}
                    ref={inputRef}
                  />
                  {inputVal &&
                  <div className='px-pappslxpal'>
                    <button onClick={()=>{setInputValue('')}}>
                      <FiDelete color='#333333' size={18} style={{marginLeft:'-5px'}}/>
                    </button>
                  </div>
                  }
              </div>

              <div className='ppxzp--ps-pac-pcpaslpl-ap'>
                  <div className='xlpap-xpa--pzaplaxa'>
                    <button className={`${nearYouOrTrending === 'trending' ? 'zppapplslls' : 'zlppppspsplll'}`} onClick={()=>setNYorTr('trending')}>Trending</button>
                    <button className={`${nearYouOrTrending === 'nearyou' ? 'zppapplslls' : 'zlppppspsplll'}`} onClick={()=>setNYorTr('nearyou')}>Near you</button>
                  </div>
              </div>
              
                {nbl ? 
              <div className='lspa-lp-sllpd-loading-small'>
                <svg xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" style={{margin:'auto', background:'#fff', display:'block'}} width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                  <g transform="translate(20 50)">
                  <circle cx="0" cy="0" r="6" fill="#02a95c">
                    <animateTransform attributeName="transform" type="scale" begin="-0.375s" calcMode="spline" keySplines="0.3 0 0.7 1;0.3 0 0.7 1" values="0;1;0" keyTimes="0;0.5;1" dur="1s" repeatCount="indefinite"></animateTransform>
                  </circle>
                  </g><g transform="translate(40 50)">
                  <circle cx="0" cy="0" r="6" fill="#02a95c">
                    <animateTransform attributeName="transform" type="scale" begin="-0.25s" calcMode="spline" keySplines="0.3 0 0.7 1;0.3 0 0.7 1" values="0;1;0" keyTimes="0;0.5;1" dur="1s" repeatCount="indefinite"></animateTransform>
                  </circle>
                  </g><g transform="translate(60 50)">
                  <circle cx="0" cy="0" r="6" fill="#02a95c">
                    <animateTransform attributeName="transform" type="scale" begin="-0.125s" calcMode="spline" keySplines="0.3 0 0.7 1;0.3 0 0.7 1" values="0;1;0" keyTimes="0;0.5;1" dur="1s" repeatCount="indefinite"></animateTransform>
                  </circle>
                  </g><g transform="translate(80 50)">
                  <circle cx="0" cy="0" r="6" fill="#02a95c">
                    <animateTransform attributeName="transform" type="scale" begin="0s" calcMode="spline" keySplines="0.3 0 0.7 1;0.3 0 0.7 1" values="0;1;0" keyTimes="0;0.5;1" dur="1s" repeatCount="indefinite"></animateTransform>
                  </circle>
                  </g>
                </svg>
              </div> : 

              <div className='lcpsplcpl'>
              {/* {Array.from({ length: 30 }, (_, index) => ( */}
              
              {all_fundraisers?.map((fundraiser: any, index: number)=>(

                  <div className='dlapslpcsa' key={index}>
                    <Link href={`/project/${fundraiser._id}`}>
                      <div className='lzppals'> 
                        
                        <div className='z-cp-cpl-llllps'>
                            <img src={FILES_URL+'/'+fundraiser.thumbnail} />
                        </div>
                        <div className='lelpwleplfw--wepfep'>
                          <h1>{fundraiser.title}</h1>
                          <span>by {fundraiser.organizer}</span>
                          
                          <div className='lslv-ra-goal fd3as kfkldsk'>
                            <div className='lsvl-goal-progess-bar' style={{background:'#e6f5ef'}}>
                              <div className='lvl-pb-progress' style={{background:'#02a95c', width:calculateProgressOfFundraiser(fundraiser.raised, Number(fundraiser.goal))+'%'}}></div>
                            </div>
                          </div>
                          <div className='lvldvfdps-raised flllall lldlppalsl'>
                            <span>{formatDonationAmount(fundraiser.raised)}</span>
                            <label>raised</label>
                          </div>
                        </div>
                      </div>


                    </Link>
                      </div>

                    ))}

                      
              </div>}

              {/* <div className='pzpc--sdpapdalp-pdsap-spdapllxlasp-d-a-sp'>
                  <div className='psp-xpp-adplxpas'>
                    <div className='z-cp-cpl-llllps'>
                        <img src="happyf.png" />
                    </div>
                    <div className='lelpwleplfw--wepfep'>
                      <h1>Support the Ambrosio Kids: In Memory of Jen & Ryan</h1>
        
                 
                    </div>
                  </div>

                  <div className='pcppppxa'>
                    <div className='clpas-pdlaplds'>


                      <div className='pcpalsplpsa' style={{marginLeft:0}}>

                        <div className='z-cp-cpl-llllps'>
                            <img src="happyf.png" />
                        </div>
                        <div className='lelpwleplfw--wepfep'>
                          <h1>Support the Ambrosio Kids: In Memory of Jen & Ryan</h1>
                       
                        </div>

                      </div>


                      <div className='pcpalsplpsa'>
                        
                        <div className='z-cp-cpl-llllps'>
                            <img src="happyf.png" />
                        </div>
                        <div className='lelpwleplfw--wepfep'>
                          <h1>Support the Ambrosio Kids: In Memory of Jen & Ryan</h1>
                          
                        
                        </div>

                      </div>
                    </div>

                    <div className='clpas-pdlaplds'>


                      <div className='pcpalsplpsa' style={{marginLeft:0}}>

                        <div className='z-cp-cpl-llllps'>
                            <img src="happyf.png" />
                        </div>
                        <div className='lelpwleplfw--wepfep'>
                          <h1>Support the Ambrosio Kids: In Memory of Jen & Ryan</h1>
                        
                        </div>

                      </div>


                      
                    </div>
                  </div>
 
              </div> */}
          </div>
        </div>
      </div>
 

      <Footer className='ablcdp2dw'/>
 
      
    </>
  )
} 
