import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import { FaPlay } from "react-icons/fa";
import SpecialBoxFrame from '@/components/special-box-frame'
import { IoMdArrowDown } from "react-icons/io";
import { FaHeart } from "react-icons/fa";
import { IoArrowDownCircleOutline } from "react-icons/io5";
import Footer from '@/components/footer'


const inter = Inter({ subsets: ['latin'] })

export default function PrivacyPolicy() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <Header />

      <div className='container-3'>
        <div className='wrapper-3'>
          
          <div className='page-cpvdl'>
            <div className='vlvldfpppspsp'>
              <h1>Refund Policy</h1>


              <p>Effective Date: 09.01.2024</p>

              <h2>1. Refund Eligibility</h2>

              <p>We strive to provide satisfaction with our products/services. Refunds may be considered under the following circumstances:</p>

              <ul>
                  <li>1.1 <strong>Product/Service Issues:</strong> If there are defects or issues with the product or service that make it unusable.</li>
                  <li>1.2 <strong>Unauthorized Purchases:</strong> In case of unauthorized transactions or purchases made without your consent.</li>
                  <li>1.3 <strong>Unmet Expectations:</strong> If the product or service does not meet the expectations outlined in the description or terms.</li>
              </ul>

              <h2>2. Refund Process</h2>

              <p>To request a refund, please follow these steps:</p>

              <ul>
                  <li>2.1 <strong>Contact Us:</strong> Reach out to our customer support team within [number of days] days of the purchase date.</li>
                  <li>2.2 <strong>Provide Details:</strong> Clearly state the reason for your refund request and provide any necessary documentation or evidence.</li>
                  <li>2.3 <strong>Review Process:</strong> Our team will review your request and notify you of the decision within a reasonable time frame.</li>
                  <li>2.4 <strong>Refund or Resolution:</strong> If approved, we will initiate a refund or provide an appropriate resolution based on the circumstances.</li>
              </ul>

              <h2>3. Non-Refundable Items</h2>

              <p>Certain items or services may not be eligible for a refund, including but not limited to [list of non-refundable items or services].</p>

              <h2>4. Changes to this Refund Policy</h2>

              <p>We may update this Refund Policy to reflect changes in our practices. Please review the policy periodically.</p>

              <h2>5. Contact Us</h2>

              <p>If you have any questions or concerns about this Refund Policy, please contact us at [your contact email].</p>


            </div>
          </div>

        </div>
      </div>

      <Footer className='ablcdp2dw'/>
 
      
    </>
  )
} 
