import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import { FaPlay } from "react-icons/fa";
import SpecialBoxFrame from '@/components/special-box-frame'
import { IoMdArrowDown } from "react-icons/io";
import { FaHeart } from "react-icons/fa";
import { IoArrowDownCircleOutline } from "react-icons/io5";
import Footer from '@/components/footer'
import HeaderNew from '@/components/header-new'


const inter = Inter({ subsets: ['latin'] })

export default function Terms() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <HeaderNew noFixed={true}/>

      <div className='container'>
        <div className='wrapper'>
          
          <div className='page-cpvdl'>
            <div className='vlvldfpppspsp'>
              <h1>RiseUpGram Terms</h1>


              <p>Effective Date: 09.01.2024</p>

              

<p>

Greetings and welcome to the RiseUpGram community! As you embark on your journey within our platform, it is essential to acquaint yourself with the governing principles encapsulated in these terms and conditions ("Terms"). These Terms delineate the parameters that regulate your interactions and engagements with the RiseUpGram website and its associated services. By choosing to access or use RiseUpGram, you willingly commit to adhering to and being bound by the provisions outlined in these Terms.
<br/>
<br/>
Your decision to explore and engage with RiseUpGram implies a recognition and acceptance of the guidelines set forth herein. We encourage you to peruse these Terms thoroughly to ensure a clear understanding of the expectations and obligations associated with your usage of our platform. Should you find any part of these Terms incompatible with your perspectives or preferences, we kindly request that you refrain from using RiseUpGram.
<br/>
<br/>

At the core of this agreement is a commitment to establishing a community founded on trust, responsibility, and shared values. These Terms are designed to create a safe, inclusive, and respectful space for all users. Your compliance with these Terms not only guarantees your seamless and secure interaction with RiseUpGram but also contributes to the collective well-being and positive experiences of our community.
<br/>
<br/>

As we embark on this shared journey, the foundation of our community's strength lies in the mutual respect and understanding fostered by these Terms. We appreciate your dedication to these principles, and we are excited to have you as an integral part of RiseUpGram. If you have any questions or require further clarification regarding these Terms, our team is readily available to assist you on your RiseUpGram adventure. Thank you for choosing RiseUpGram, where your endeavors can rise and make a lasting impact!



</p>
<p>&nbsp;</p>

<h2>1. User Accounts</h2>

<h3>1.1 Account Creation</h3>


<p>
The creation of a user account on RiseUpGram is a pivotal step that opens the gateway to a plethora of comprehensive features and functionalities. This process entails a commitment from users to provide information that is not only accurate but also current and all-encompassing. Users are required to furnish a diverse range of details during the registration process, covering personal information and the specifics of the campaigns they intend to create or support. This commitment is integral to fostering a robust and reliable user profile, facilitating a personalized and impactful engagement with the platform.
<br/>
<br/>
Within this commitment lies a critical responsibility bestowed upon users – the duty to maintain the utmost confidentiality and security of their account information. Users are entrusted with the guardianship of their personal details, necessitating a proactive approach to prevent any unauthorized access or misuse. This emphasis on confidentiality underscores the significance of user awareness and diligence in safeguarding sensitive data within the secure confines of the RiseUpGram platform.
<br/>
<br/>

Furthermore, this commitment is not merely a procedural formality; it is a cornerstone of responsible and ethical digital citizenship within the RiseUpGram community. Users play a pivotal role in upholding the integrity of their personal information, contributing substantially to the overall security and trustworthiness of the platform. The collaborative effort to ensure responsible account management is crucial for fostering a secure and trustworthy online environment for all users.
<br/>
<br/>

By highlighting the multifaceted nature of this commitment, RiseUpGram seeks to empower users with the knowledge and understanding necessary to navigate the platform responsibly. It is not just about creating an account; it is about becoming an active and conscientious participant in a community-driven space where security, transparency, and trust are paramount. In embracing this commitment, users not only gain access to the full array of features but also become integral contributors to the ethos of RiseUpGram – a platform dedicated to positive impact, ethical engagement, and the collective empowerment of its community members.

</p>

<h3>1.2 Accurate Information</h3>

<p>
Ensuring the authenticity and currency of information is paramount within the RiseUpGram community. Users commit to furnishing truthful and up-to-date details during the account creation process, emphasizing transparency and integrity. The responsibility extends beyond the initial registration; users are entrusted with the ongoing task of regularly updating this information. This commitment to keeping details current is integral to maintaining the accuracy and effectiveness of user profiles. As stewards of their own information, users play a vital role in cultivating a trustworthy and dynamic environment within RiseUpGram, where reliable and updated information is the bedrock of meaningful and impactful interactions.

</p>
<h3>1.3 Security</h3>

<p>
Emphasizing the paramount significance of account security, RiseUpGram underscores that users bear the sole responsibility for all activities transpiring under their respective accounts. This stewardship role extends to vigilance in monitoring and safeguarding the account against any potential unauthorized use. In the event of even a suspicion or indication of unauthorized access, users are urged to promptly report such instances to RiseUpGram. This proactive reporting serves as the initial step towards a thorough investigation and swift resolution by the RiseUpGram team. By fostering this collaborative approach, we prioritize the security of our users and the overall integrity of the RiseUpGram community.
</p>

<p>&nbsp;</p>

<h2>2. Campaigns and Donations</h2>

<h3>2.1 Campaign Creation</h3>
<p>
RiseUpGram serves as an innovative and inclusive platform, providing users with the unique opportunity to create and propel campaigns that resonate with personal aspirations, charitable causes, or community-driven endeavors. The versatility of RiseUpGram lies in its capacity to cater to a spectrum of purposes, allowing individuals and organizations to harness the collective power of the online community for positive change.
<br/>
<br/>
A distinguishing hallmark of RiseUpGram is its unwavering commitment to a fee-free model. In essence, this means that when users generously contribute to a campaign, the entirety of their donation is channeled directly to the intended cause or initiative, without any deductions or fees imposed by the platform. This transparent and equitable approach ensures that the impact of every donation is maximized, enabling campaigners to achieve their objectives with the full support of the community.
<br/>
<br/>

By adopting a fee-free model, RiseUpGram takes a bold stance in aligning its mission with the principles of fairness, transparency, and community empowerment. Unlike traditional fundraising platforms, where administrative fees may diminish the overall funds available for the cause, RiseUpGram stands as a beacon of integrity, ensuring that the entire donated amount goes where it is needed the most.
<br/>
<br/>

This commitment not only distinguishes RiseUpGram as a socially responsible platform but also resonates with its overarching philosophy of fostering positive change and collective impact. By eliminating financial barriers and facilitating a direct channel between donors and campaigners, RiseUpGram strives to democratize fundraising, making it accessible and impactful for all.
<br/>
<br/>

As users engage with RiseUpGram, they become not just contributors but active participants in a community-driven movement. Whether supporting personal aspirations, charitable causes, or community projects, every user becomes a catalyst for change, contributing to the creation of a world where generosity knows no bounds. RiseUpGram is not just a platform; it is a catalyst for positive transformation, where each campaign is a testament to the potential of collective action and the boundless capacity for good within the RiseUpGram community.


</p>

<h3>2.2 Donations</h3>


<p>
Within the vibrant ecosystem of RiseUpGram, donors emerge as pivotal architects of positive change. Their role transcends mere financial support; they are integral contributors to the ethos of communal empowerment. To ensure a streamlined donation process, donors are encouraged to furnish precise and valid payment information, laying the foundation for a seamless and efficient transaction experience.
<br/>
<br/>

A notable hallmark of RiseUpGram's commitment to transparency and generosity is the absence of any fees on donations. This unique approach ensures that every ounce of support extended by donors directly amplifies the impact of the intended cause or campaign. By refraining from imposing fees, RiseUpGram upholds the principle that the entirety of donors' contributions should go where they are intended—towards making a meaningful and tangible difference.
<br/>
<br/>

This fee-free model not only distinguishes RiseUpGram within the landscape of crowdfunding platforms but also represents a conscious choice to prioritize the interests of both campaigners and donors. It signifies a departure from traditional models where platforms may deduct a percentage of donations for operational costs. In contrast, RiseUpGram is committed to preserving the sanctity of every donor's contribution, recognizing the profound significance of their trust and generosity.
<br/>
<br/>

By allowing donors to maximize the impact of their contributions, RiseUpGram transforms the act of giving into a more meaningful and empowering experience. It not only facilitates financial support but also fosters a sense of community and shared purpose. Donors become catalysts for change, knowing that their contributions, regardless of size, play an instrumental role in driving positive outcomes.
<br/>
<br/>

As donors engage with RiseUpGram, they become integral partners in a collective journey towards creating a world where compassion knows no boundaries. Their participation embodies the spirit of altruism, fostering an environment where every donation, regardless of scale, becomes a catalyst for transformative impact. In the RiseUpGram community, the generosity of donors is not just acknowledged; it is celebrated as an indispensable force propelling campaigns and causes toward success.





</p>

<h2>3. Content Guidelines</h2>

<h3>3.1 Prohibited Content</h3>

<p>
The preservation of a secure and nurturing community stands as a cornerstone of RiseUpGram's mission. To uphold this commitment, users are explicitly prohibited from initiating campaigns or posting content that is illegal, fraudulent, or contravenes any applicable laws or regulations. This prohibition extends to activities that undermine the integrity of the platform or compromise the well-being of its community members.
<br/>
<br/>

RiseUpGram, in its dedication to maintaining a positive and ethical environment, reserves the right to take swift action against any content that runs afoul of these terms. This includes the authority to promptly remove any campaigns or content that violate the established guidelines.
<br/>
<br/>

This stringent stance against illegal or fraudulent activities serves not only to protect the community but also to fortify the trust that users place in RiseUpGram. By fostering a culture of compliance and accountability, RiseUpGram endeavors to create a space where users can engage with confidence, assured that the platform actively monitors and addresses any activities that could jeopardize the safety and integrity of the community.
<br/>
<br/>

In embracing these guidelines, RiseUpGram not only fulfills its responsibility to create a secure space but also empowers users to participate in a community that values transparency, legality, and ethical conduct. Each user plays a pivotal role in contributing to the collective well-being of the community, ensuring that RiseUpGram remains a platform synonymous with trust, reliability, and positive impact.






</p>

<h3>3.2 Intellectual Property</h3>

<p>

While users maintain ownership of the content they generate, utilizing RiseUpGram involves granting the platform a non-exclusive license. This license empowers RiseUpGram to use, display, and distribute the content on the platform, thereby facilitating the showcasing of inspiring stories and campaigns within the community.
<br/>
<br/>

This non-exclusive license signifies a collaborative understanding between users and RiseUpGram. It allows the platform the flexibility to feature user-generated content across its interface, fostering an environment where impactful campaigns and stories can be shared, celebrated, and amplified. The intent behind this license is to provide a space where the richness of the RiseUpGram community can be dynamically presented, inspiring others to participate and contribute to the positive momentum.
<br/>
<br/>

This licensing arrangement doesn't diminish or infringe upon the ownership rights retained by users; rather, it forms the basis for a symbiotic relationship. Users' ownership ensures that they have control and agency over their creations, while the non-exclusive license enables RiseUpGram to curate a compelling and diverse narrative that reflects the collective spirit and impact of the community.
<br/>
<br/>

By embracing this licensing framework, RiseUpGram endeavors to celebrate the creative expressions of its users, acknowledging their role as storytellers and catalysts for positive change. It is a collaborative approach that transforms the platform into a canvas where each user's contribution becomes a brushstroke in the vibrant tapestry of RiseUpGram's collective journey.






</p>

<h2>4. Privacy</h2>

<h3>4.1 Privacy Policy</h3>
<p>
Safeguarding user privacy is a paramount commitment for RiseUpGram. By engaging with the platform, users willingly consent to the stipulations articulated in our Privacy Policy. We strongly recommend that users take the time to thoroughly review the Privacy Policy, as it provides comprehensive insights into the methods employed for collecting, utilizing, and disclosing personal information.
<br/>
<br/>

This Privacy Policy serves as a guiding document, outlining the principles and practices governing the handling of user data within RiseUpGram. It encapsulates our dedication to transparency, outlining the types of information collected, the purposes for which it is utilized, and the measures in place to ensure its secure handling.
<br/>
<br/>

Understanding the Privacy Policy is essential for users to make informed decisions about their engagement with RiseUpGram. It elucidates the mechanisms by which personal information is employed to enhance user experience, tailor content, and, most importantly, maintain the security and confidentiality of user data.
<br/>
<br/>

By fostering a culture of transparency and user agency, RiseUpGram aims to instill confidence in its community members. The Privacy Policy is not merely a legal formality but a testament to our commitment to respecting user privacy and ensuring that their online experiences are conducted in a secure and ethical manner.
<br/>
<br/>

As users navigate the RiseUpGram platform, we encourage them to embrace this spirit of transparency and engage in an informed manner, secure in the knowledge that their privacy is a fundamental priority. We appreciate and value the trust our users place in us, and we are dedicated to upholding the highest standards of privacy protection within the RiseUpGram community.

</p>

<h2>5. Payment Processing</h2>

<h3>5.1 Secure Transactions</h3>

<p>
To fortify the security of financial transactions on RiseUpGram, we have implemented a robust system utilizing a secure third-party payment processor. This strategic choice ensures that all payment information provided by users undergoes a stringent encryption process and is securely processed. The encryption methodology acts as a protective shield, safeguarding users' sensitive data from unauthorized access and potential breaches.
<br/>
<br/>
This commitment to employing a secure payment processor underscores our dedication to the utmost privacy and security standards. Users can trust that their financial information is handled with the highest level of care and diligence, minimizing any risks associated with online transactions.
<br/>
<br/>
The use of encryption technology serves as an additional layer of defense, creating a secure tunnel through which payment information travels. This encryption guarantees that even if intercepted, the data remains indecipherable and confidential. By adopting these advanced security measures, RiseUpGram aims to instill confidence in users, assuring them that their financial transactions are conducted with the highest standards of privacy and protection.
<br/>
<br/>
Our proactive approach to security aligns with our broader commitment to providing a trustworthy and dependable platform for users to engage in meaningful campaigns and contribute to impactful causes. We continuously monitor and update our security measures to stay ahead of evolving threats, ensuring that users can focus on making a positive impact without any concerns about the safety of their sensitive information.
</p>


<h3>5.2 Payment Authorization</h3>

<p>
When users initiate a transaction on RiseUpGram, it serves as a clear indication of their authorization for the payment processor to execute the transaction by charging the specified amount to the designated payment method. This deliberate action signifies users' explicit consent for the financial transaction to take place.
<br/>
<br/>
Crucially, users bear the responsibility of ensuring that they possess the necessary authorization to employ the chosen payment method. This includes verifying that the payment method used is valid, not compromised, and complies with any relevant legal and regulatory requirements. By initiating a transaction, users affirm that they have the rightful authority to engage in the financial transaction through the selected payment method.
<br/>
<br/>
This emphasis on user responsibility aligns with RiseUpGram's commitment to maintaining ethical and lawful financial practices. It is imperative for users to exercise due diligence in ensuring the legitimacy and validity of their chosen payment method, fostering a secure and trustworthy environment for all financial transactions on the platform.
<br/>
<br/>
RiseUpGram encourages users to approach financial transactions with a conscientious mindset, emphasizing the significance of authorization and legitimacy in contributing to a safe and reliable community space for fundraising and supporting impactful causes.
</p>

<h3>5.3 Refunds</h3>

<p>
Although RiseUpGram is committed to delivering a reliable platform, it acknowledges that occasional errors or disputes may arise in the course of interactions. In such instances, users are encouraged to promptly reach out to RiseUpGram's dedicated support team for assistance. The support team is equipped to address queries, resolve concerns, and provide guidance on navigating any challenges that may arise during the use of the platform.
<br/>
<br/>
Refunds, when warranted, will be issued in strict adherence to RiseUpGram's refund policy. This policy, comprehensive and accessible, is detailed in our help center to ensure transparency and clarity. Users are encouraged to familiarize themselves with the refund policy, gaining a clear understanding of the procedures and criteria under which refunds may be processed.
<br/>
<br/>
This commitment to a clear and accessible refund policy reflects RiseUpGram's dedication to fairness and user satisfaction. By providing a structured framework for addressing errors or disputes, RiseUpGram seeks to instill confidence in users, assuring them that their concerns will be handled with diligence and in accordance with established guidelines.
<br/>
<br/>
The support team at RiseUpGram stands ready to assist users in navigating any challenges they may encounter, underscoring our commitment to providing a positive and supportive environment for all community members. The goal is to ensure that users' experiences on RiseUpGram are not only impactful but also backed by responsive and reliable support mechanisms.
</p>

<h3>5.4 Third-Party Payment Processor</h3>

<p>
RiseUpGram's operational framework involves the utilization of a third-party payment processor to facilitate financial transactions. Users engaging in transactions on the platform are obligated to align with and adhere to the terms and conditions stipulated by the payment processor, in conjunction with the overarching Terms of Use outlined by RiseUpGram.
<br/>
<br/>
It is imperative for users to recognize that RiseUpGram assumes no responsibility for the actions or policies of the payment processor. As an independent entity providing a platform for fundraising and community engagement, RiseUpGram operates in partnership with the payment processor to ensure the secure and efficient handling of financial transactions. However, the terms and conditions, as well as the policies of the payment processor, are distinct and supplementary to those outlined by RiseUpGram.
<br/>
<br/>
Users are encouraged to review and comprehend the terms set forth by the payment processor to facilitate a comprehensive understanding of their rights, responsibilities, and any specific procedures governing financial transactions. This collaborative approach ensures a seamless and secure user experience, with users and the payment processor each contributing to the overall integrity of the financial ecosystem within RiseUpGram.
<br/>
<br/>
By clearly delineating the separation of responsibilities between RiseUpGram and the payment processor, this statement aims to establish transparency and clarity regarding the distinct roles and obligations of each entity in the user experience. It is a testament to RiseUpGram's commitment to fostering an environment where financial transactions are conducted with the highest standards of security and adherence to established protocols.
</p>

<h2>6. General</h2>

<h3>6.1 Modification of Terms</h3>

<p>

RiseUpGram maintains the prerogative to modify or update these Terms at its discretion. Users can expect to be informed of any material changes either through email communication or notifications within the platform. It is crucial for users to stay informed about updates, as the continued use of RiseUpGram after the effective date of any revised Terms signifies their acceptance of the modifications.
<br/>
<br/>
This approach to communicating changes underscores RiseUpGram's commitment to transparency and user awareness. By promptly notifying users of any substantial alterations to the Terms, we aim to empower users with the information needed to make informed decisions about their continued engagement with the platform.
<br/>
<br/>
The acknowledgment and acceptance of revised Terms through continued usage serve as a practical mechanism for users to actively engage with and adapt to any updates that may impact their experience on RiseUpGram. Users are encouraged to regularly review the Terms to stay informed about any modifications that could affect their rights, obligations, or overall engagement within the RiseUpGram community.
<br/>
<br/>
This commitment to clear communication and user consent reflects RiseUpGram's dedication to maintaining a trustworthy and collaborative relationship with its community. The goal is to ensure that users are well-informed, engaged, and able to navigate the platform with confidence and understanding.
</p>

<h3>6.2 Governing Law</h3>

<p>
These Terms are intricately governed by and construed in accordance with the laws of the United States, forming the legal foundation that defines the parameters of user engagement on RiseUpGram. This jurisdictional alignment ensures that the interpretation and enforcement of these Terms are guided by the legal framework established within the United States.
<br/>
<br/>
In the event of any disputes arising under or in connection with these Terms, users and RiseUpGram commit to navigating legal resolutions within the exclusive jurisdiction of the courts located in the United States. This clause is not just a legal formality; it is a crucial aspect of defining the scope and nature of any potential legal proceedings related to user interactions with RiseUpGram.
<br/>
<br/>
By specifying the United States as the jurisdiction for governing these Terms and resolving disputes, RiseUpGram aims to provide users with a transparent understanding of the legal context within which their rights and obligations are defined. It underscores the platform's commitment to upholding legal standards and facilitating a clear and consistent legal framework for its global user base.
<br/>
<br/>
Users are encouraged to familiarize themselves with the jurisdiction clause, as it serves as an essential component of the Terms that govern their interactions on RiseUpGram. This commitment to legal transparency reflects RiseUpGram's dedication to establishing a trustworthy and accountable environment for its diverse community of users.
</p>

<h3>6.3 User Responsibilities</h3>

<p>In addition to the responsibilities outlined in the account creation section, users are encouraged to engage responsibly within the RiseUpGram community. Respectful communication and adherence to ethical standards are essential. Any misuse or violation of these principles may result in account termination.</p>

<h3>6.4 Community Guidelines</h3>

<p>RiseUpGram is built on the principles of inclusivity, kindness, and support. We expect all users to adhere to community guidelines that promote a positive environment. This includes refraining from engaging in any form of discrimination, harassment, or harmful behavior. Violation of these guidelines may result in appropriate actions, including but not limited to content removal and account suspension.</p>

<h3>6.5 User Feedback</h3>

<p>RiseUpGram values the feedback of its users as it helps in enhancing and improving the platform. Users are encouraged to share their experiences, suggestions, and concerns through our designated feedback channels. Insights provided by users contribute to the continuous development and betterment of our community.</p>

<h3>6.6 Communication Channels</h3>

<p>RiseUpGram provides various communication channels, including but not limited to emails, notifications, and in-app messages. Users agree to receive communications from RiseUpGram related to their account, campaigns, and important platform updates. Users can manage their communication preferences within their account settings.</p>

<h3>6.7 Third-Party Links</h3>

<p>RiseUpGram may contain links to third-party websites or services. These links are provided for convenience and informational purposes. RiseUpGram does not endorse or take responsibility for the content or practices of third-party sites. Users access such links at their own risk and are encouraged to review the terms and privacy policies of external websites.</p>

<h3>6.8 Disclaimer of Warranties</h3>

<p>RiseUpGram strives to provide a reliable and secure platform. However, users acknowledge and agree that the use of RiseUpGram is at their own risk. RiseUpGram makes no warranties, expressed or implied, regarding the accuracy, reliability, or availability of the platform. We reserve the right to modify, suspend, or discontinue any part of the service at any time.</p>

<h3>6.9 Limitation of Liability</h3>

<p>To the maximum extent permitted by law, RiseUpGram, its affiliates, and its contributors shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from the use of the platform.</p>
 

<h2>7. Modification of Terms</h2>

<p>RiseUpGram reserves the right to modify or update these Terms at any time. Users will be notified of material changes via email or through the platform. Continued use of RiseUpGram after the effective date of the revised Terms constitutes acceptance of the changes.</p>
<p>These Terms are governed by and construed in accordance with the laws of USA. Any disputes arising under or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts located in USA.</p>

<p>For any questions, concerns, or feedback regarding these Terms, please contact contact@riseupgram.com.</p>

<p>Thank you for your commitment to RiseUpGram, where together, we can make a positive impact on the world!</p>

            </div>
          </div>

        </div>
      </div>

      <Footer className='ablcdp2dw'/>
 
      
    </>
  )
} 
