import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import { FaPlay } from "react-icons/fa";
import SpecialBoxFrame from '@/components/special-box-frame'
import { IoMdArrowDown } from "react-icons/io";
import { FaHeart } from "react-icons/fa";
import { IoArrowDownCircleOutline } from "react-icons/io5";
import Footer from '@/components/footer'
import { useEffect, useState } from 'react'
import { CiWarning } from "react-icons/ci";


const inter = Inter({ subsets: ['latin'] })

export default function Donate() {

//   const [inputValue, setInputValue] = useState<string>('');
  const [inputValue, setInputValue] = useState<number | string>('');
  const [isErrorDNValue, setErrorDonationValue] = useState<boolean>(false);
  const [choosePaymentMethod, setPaymentMethod] = useState<number>(3);


  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    // Use a regular expression to allow only numeric input
    // const numericInput = event.target.value.replace(/[^0-9]/g, '');

    // setInputValue(numericInput);
    const value = event.target.value;

    // Check if the value is numeric and has 5 or fewer digits
    // if (/^\d*$/.test(value) && value.length <= 5 && Number(value) >= 1) {
    if (/^\d*$/.test(value) && value.length <= 5) {
      setInputValue(value);
    }
  };

  useEffect(()=>{
    if(Number(inputValue) > 50000){ 
        setErrorDonationValue(true);
    }else{
        setErrorDonationValue(false);
    }
  }, [inputValue])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          {`
            body {
              background: #faf8f6 !important;
              /* Add more styles as needed */
            }
          `}
        </style>
      </Head>
    
       
    <Header />

    <div className='dpq-dqwlsls'>

        <div className='donate-welfw'>
            <div className='p1pdwelqll'>
                <div className='llqld-11d'>
                    <img src="/alalaaaa.png" />
                </div>

                <div className='spclap-111ds'>
                    <span>You're supporting <b>{'Support the Ambrosio Kids: In Memory of Jen & Ryan'}</b></span>
                    <label>Your donation will benefit <b>{'Brandi Burke'}</b></label>
                </div>
            </div>

            <div className='pdpqp111sla--da-ssxz'>
                <div className='cpapl1'>
                    <span>Enter your donation</span>
                </div>
                <div className={`cpapcplsal1112 ${isErrorDNValue && 'error'}`}>
                    <div className='cpa1l2'>
                        <span>$</span>
                        <label>USD</label>
                    </div>
                    {/* <input inputMode='numeric'/> */}
                    <input
                        type="text"
                        id="numericInput"
                        value={inputValue}
                        onChange={handleInputChange} 
                    />
                    <div className='dpspaql'>
                        <span>.00</span> 
                    </div>
                </div>

                {isErrorDNValue && 
                    <div className='spdp11'>
                        <div className='cp1pdl'>
                            <CiWarning size={22} color='#cf364a'/>
                        </div>
                        <span>Donation limit is $50,000.00</span>
                    </div>
                }
            </div>

            <div className='vpp1ll32lcedl'>
                <span>We don't charge fees on this fundraiser.</span>
                <p>GoFundMe has a 0% platform fee for organizers. GoFundMe will continue offering its services thanks to donors who will leave an optional amount here</p>
            </div>

            <div className='cpp1pldw-separator'></div>

            <div className='pcl12pl-3-21'>
                <div className='pv-e-1dpqq cllalla'>
                    <span>Payment method</span>
                    <p>* This fundraiser support only payments with <b>credit or debit.</b></p>
                </div>

                <div className='p1pd-12sl-pmth'>
                    
                    <div className='vlspa--qffd'>

                        <button className='pcp1lded-v-dpckmd' onClick={()=>{setPaymentMethod(4)}}>
                            {/* <div className='gfv-dpw'></div> */}
                            <div className={`gfv-dpw ${choosePaymentMethod === 4 && 'pdapd11sw'}`}>
                                <div></div>
                            </div>
                            <div className='bbfnfms-a'>
                                <img src="/paypal.png" />
                            </div>
                            <div className='cpps1-decvff'>
                                <span>Paypal (not supporterd)</span>
                            </div>
                        </button>

                        {choosePaymentMethod === 4 &&
                        <div className='vpds-axla'>
                            <p>This fundraiser at the moment dosent accept payments that are made throw PayPal. You can use another Payment Method.</p>
                        </div>}

                    </div>

                    <div className='vlspa--qffd'>

                        <button className='pcp1lded-v-dpckmd' onClick={()=>{setPaymentMethod(1)}}>
                            {/* <div className='gfv-dpw'></div> */}
                            <div className={`gfv-dpw ${choosePaymentMethod === 1 && 'pdapd11sw'}`}>
                                <div></div>
                            </div>
                            <div className='bbfnfms-a'>
                                <img src="/venmo.png" />
                            </div>
                            <div className='cpps1-decvff'>
                                <span>Venmo (not supporterd)</span>
                            </div>
                        </button>

                        {choosePaymentMethod === 1 &&
                        <div className='vpds-axla'>
                            <p>This fundraiser at the moment dosent accept payments that are made throw Venmo. You can use another Payment Method.</p>
                        </div>}

                    </div>
                    <div className='vlspa--qffd'>
                        <button className='pcp1lded-v-dpckmd' onClick={()=>{setPaymentMethod(2)}}>
                            {/* <div className='gfv-dpw'></div> */}
                            <div className={`gfv-dpw ${choosePaymentMethod === 2 && 'pdapd11sw'}`}>
                                <div></div>
                            </div>
                            <div className='bbfnfms-a dpasx'>
                                <img src="/googlepay.png" />
                            </div>
                            <div className='cpps1-decvff'>
                                <span>Google Pay (not supported)</span>
                            </div>
                        </button>
                        {choosePaymentMethod === 2 &&
                        <div className='vpds-axla'>
                            <p>This fundraiser at the moment dosent accept payments that are made throw Google Pay. You can use another Payment Method.</p>
                        </div>}
                    </div>


                    <div className='vlspa--qffd vpapxas'>


                        <button className='pcp1lded-v-dpckmd vpapxas' onClick={()=>{setPaymentMethod(3)}}>
                            <div className={`gfv-dpw ${choosePaymentMethod === 3 && 'pdapd11sw'}`}>
                                <div></div>
                            </div>
                            <div className='bbfnfms-a dpasx'>
                                <img src="/creditordebit.png" />
                            </div>
                            <div className='cpps1-decvff'>
                                <span>Credit or debit</span>
                            </div>
                        </button>

                        {choosePaymentMethod === 3 &&
                        <div className='vpds-axla'>

                            <div className='vppsaxlaf4e'> 
                                <div className='clspxlaxs'>
                                    <label>Email address</label>
                                    <input placeholder='john@mail.com'/>
                                </div>
                                <div className='pxa1pixals'>

                                    <div className='clspxlaxs'>
                                        <label>First name</label>
                                        <input placeholder='John'/>
                                    </div>

                                    
                                    <div className='clspxlaxs cvlopa'>
                                        <label>Last name</label>
                                        <input placeholder='Adison'/>
                                    </div>
                                </div>


                                <div className='clspxlaxs vlzlaaa'>
                                    <label>Card number</label>
                                    <input placeholder='XXXX XXXX XXXX XXXX'/>
                                </div>

                                <div className='pxa1pixals'>

                                    <div className='clspxlaxs'>
                                        <label>MM/YY</label>
                                        <input placeholder='15/26'/>
                                    </div>

                                    
                                    <div className='clspxlaxs cvlopa'>
                                        <label>CVV</label>
                                        <input placeholder='***'/>
                                    </div>
                                </div>

                                <div className='clspxlaxs vlzlaaa'>
                                    <label>Name on card</label>
                                    <input placeholder='John Adison'/>
                                </div>

                                <div className='pxa1pixals'>

                                    <div className='clspxlaxs'>
                                        <label>Country</label>
                                        <input placeholder='United States'/>
                                    </div>

                                    
                                    <div className='clspxlaxs cvlopa'>
                                        <label>Postal code</label>
                                        <input placeholder='431sfs'/>
                                    </div>
                                </div>
                            </div>
                        </div>}
                    
                    </div>

                </div>
            </div>
        </div>

    </div>      


    <Footer className='home-footer'/>
 
      
    </>
  )
} 
